### ISSUE TITLE
The descriptions start with "The image depicts/features" instead of going directly to the object

### ISSUE THREAD

**Issue by TonyLianLong** [UCSC-VLAA/Recap-DataComp-1B#5]
Thanks for the great work! I'm trying out your prompt with a [llava hf space](https://huggingface.co/spaces/badayvedat/LLaVA). However, rather than directly getting to the point ("A [object name] ...", which is often the case in your Fig. 1), the model's outputs often start with "the image ...". Is there anything I missed when prompting?

<img width="1352" alt="image" src="https://github.com/UCSC-VLAA/Recap-DataComp-1B/assets/1451234/fc445700-b87f-4e4c-a6f7-e2d8524324ef">

**Comment by LinB203** [comment]
same question.

**Comment by ImKeTT** [comment]
Which conversation template are you guys using? We employed the LLaMA3 conversation template for our LLaMA3-powered LLaVA.

**Comment by cihangxie** [comment]
I do not think it relates to the prompt; rather, I believe this behavior may partially relate to the fact that we also finetune LLaVA with the [HQ-Edit](https://thefllood.github.io/HQEdit_web/) dataset, which can help to avoid the  "The image"-like outputs. You can try our reception model (with your own prompt) [here](https://huggingface.co/tennant/llava-llama-3-8b-hqedit)

**Comment by cihangxie** [comment]
I close this issue for now; but feel free to reopen it if you still meet this issue with our reception model.

**Comment by YunjieYu** [comment]
> I do not think it relates to the prompt; rather, I believe this behavior may partially relate to the fact that we also finetune LLaVA with the [HQ-Edit](https://thefllood.github.io/HQEdit_web/) dataset, which can help to avoid the "The image"-like outputs. You can try our reception model (with your own prompt) [here](https://huggingface.co/tennant/llava-llama-3-8b-hqedit)

Can you tell us how to use your reception model? I have tried to load your model with transformers, but failed.
