### ISSUE TITLE
Mapping to original Datacomp-1b

### ISSUE THREAD

**Issue by YoadTew** [UCSC-VLAA/Recap-DataComp-1B#7]
Hi,

Thank you for the excellent work!

I would like to use this dataset, but I also need the original Datacomp npz files with VIT-L/14 embeddings for each caption in the dataset.

Is there a way to map from the .parquet files in your dataset (https://huggingface.co/datasets/UCSC-VLAA/Recap-DataComp-1B/tree/main/data/train_data) to the corresponding .parquet files in the original Datacomp data (https://huggingface.co/datasets/mlfoundations/datacomp_1b/tree/main)?

I noticed that your dataset contains 3,550 files, whereas the original Datacomp dataset contains 2,664 files.

Thank you!

**Comment by ImKeTT** [comment]
Thank you for your interest in our work! 
Unfortunately, you cannot directly map our Recaption-DataComp-1B shards to the original HF DataComp-1B shards. But you can always use the `sha256` or the `key` feature to map every instance from the recaption DataComp to the original DataComp.
