### ISSUE TITLE
The performance of Recap-CLIP-ViT-H/14 on ImageNet

### ISSUE THREAD

**Issue by viyjy** [UCSC-VLAA/Recap-DataComp-1B#8]
Thanks for your great work. I didn't find the performance of Recap-CLIP-ViT-H/14 on ImageNet in your paper, did I miss anything? Thanks.

**Comment by xhl-video** [comment]
Hi, thank you for your interest! We have released the [Recap-CLIP-Large_16 with **Huge-size text encoder**](https://huggingface.co/UCSC-VLAA/ViT-L-16-HTxt-Recap-CLIP). The vision encoder is a large-size ViT. We have yet to train a ViT-H/14 model. We have fixed the model card's name. I'm sorry for the confusion.

**Comment by viyjy** [comment]
"Table 2: Recap-CLIP model configurations used in our paper" in [arxiv](https://arxiv.org/pdf/2406.08478) shows `H/14`, so I thought you have a H/14 trained on this new dataset. Never mind, thanks!
